apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logic-apps-anywhere-demo.fullname" . }}-secrets
  labels:
    app: {{ template "logic-apps-anywhere-demo.name" . }}
    chart: {{ template "logic-apps-anywhere-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  functionStorage: {{ .Values.secrets.functionStorage | b64enc | quote }}